export const metadata = { title: 'Terms & Conditions - Career Forge' }

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 prose">
      <h1 className="text-3xl font-bold mb-2">Terms &amp; Conditions</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: June 2026</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">1. Acceptance of Terms</h2>
      <p>By creating an account and using Career Forge, you agree to these Terms &amp;
      Conditions. If you do not agree, please do not use the service.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">2. Description of Service</h2>
      <p>Career Forge is a tool that helps you build a resume/CV and cover letter tailored
      to a target job description. It uses AI to parse your resume, identify skill gaps,
      ask follow-up questions, and generate updated resume content, cover letters, and
      pre-flight eligibility guidance.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">3. AI-Generated Content</h2>
      <p>Content generated by Career Forge — including rewritten resume bullet points,
      cover letters, skill suggestions, and pre-flight guidance — is produced by an AI
      model and may contain inaccuracies. <strong>You are solely responsible for reviewing,
      editing, and verifying all generated content before using it</strong> in a job
      application. Career Forge does not guarantee the accuracy, completeness, or
      truthfulness of any generated content, and you must not submit false information to
      an employer.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">4. Pre-Flight Guidance Disclaimer</h2>
      <p>Pre-flight checks (e.g. visa sponsorship, work authorization, driving licence,
      relocation) are general guidance based on information you provide and information
      found in a job description. They are not legal, immigration, or employment advice.
      Always verify your eligibility directly with the employer or a qualified
      professional.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">5. Your Account</h2>
      <p>You are responsible for maintaining the confidentiality of your account
      credentials and for all activity under your account. You must provide accurate
      information when creating an account.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">6. Acceptable Use</h2>
      <p>You agree not to use Career Forge to generate content that is fraudulent,
      defamatory, discriminatory, or that misrepresents your qualifications, identity, or
      work history in a way intended to deceive an employer.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">7. Intellectual Property</h2>
      <p>You retain ownership of the content you upload (your resume, job descriptions, and
      answers) and the documents generated for you. You grant us a limited licence to
      process this content solely to provide the service to you.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">8. Service Availability</h2>
      <p>Career Forge is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We do not
      guarantee uninterrupted availability and may modify or discontinue features at any
      time.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">9. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, Career Forge and its operators are not
      liable for any indirect, incidental, or consequential damages arising from your use
      of the service, including outcomes of job applications.</p>

      <h2 className="text-xl font-semibold mt-8 mb-2">10. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. Continued use of the service after
      changes constitutes acceptance of the revised Terms.</p>
    </div>
  )
}
